inputs:
  shell:
    description: 'shell for running make'
    required: true
  path:
    description: 'add to PATH env variable'
    required: false
  cpath:
    description: 'assign CPATH env variable'
    required: false
    default: '${CPATH}'
  library_path:
    description: 'assign LIBRARY_PATH env variable'
    required: false
    default: '${LIBRARY_PATH}'

runs:
  using: "composite"
  steps:
    - name: Setup Win Vars
      if: runner.os == 'Windows'
      run: |
        echo "${{ inputs.path }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "CPATH=${{ inputs.cpath }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "LIBRARY_PATH=${{ inputs.library_path }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: ${{ inputs.shell }}
    - name: Setup Unix Vars
      if: runner.os != 'Windows'
      run: |
        echo "${{ inputs.path }}" >> $GITHUB_PATH
        echo "CPATH=${{ inputs.cpath }}" >> $GITHUB_ENV
        echo "LIBRARY_PATH=${{ inputs.library_path }}" >> $GITHUB_ENV
      shell: ${{ inputs.shell }}

