inputs:
  shell:
    description: 'shell for running xcode'
    required: true
  working-directory:
    description: 'path to working directory'
    required: true

runs:
  using: "composite"
  steps:
    - name: XCode Build
      working-directory: ${{ inputs.working-directory }}
      run: xcodebuild -scheme ALL_BUILD
      shell: ${{ inputs.shell }}
    - name: XCode Test
      working-directory: ${{ inputs.working-directory }}
      run: xcodebuild -scheme RUN_TESTS
      shell: ${{ inputs.shell }}
    - name: XCode Install
      working-directory: ${{ inputs.working-directory }}
      run: xcodebuild -scheme install
      shell: ${{ inputs.shell }}

