dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs:
  - ../../lib

executables:
  isPalindrome-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - isPalindrome

