inputs:
  shell:
    description: 'shell for running make'
    required: true
  cpath:
    description: 'assign CPATH env variable'
    required: false
    default: '${CPATH}'
  library_path:
    description: 'assign LIBRARY_PATH env variable'
    required: false
    default: '${LIBRARY_PATH}'

runs:
  using: "composite"
  steps:
    - name: Setup Env
      run: |
        echo "CPATH=${{ inputs.cpath }}" >> $GITHUB_ENV
        echo "LIBRARY_PATH=${{ inputs.library_path }}" >> $GITHUB_ENV
      shell: ${{ inputs.shell }}

